# Site settings
title: Pallidocs
description: >-
  Pallidocs website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
navigation:
- label: Films
  link: "/roommates/"
- label: Forms
  link: "/forms/"
- label: Contact
  link: "/contact/"
collections:
  assets:
    title: Assets
    output: true
# Build settings
markdown: kramdown
